export const GROUPMANAGER_FEATURE_EDIT_REQUEST = "GROUPMANAGER_FEATURE_EDIT_REQUEST";
export const GROUPMANAGER_FEATURE_EDIT_SUCCESS = "GROUPMANAGER_FEATURE_EDIT_SUCCESS";
export const GROUPMANAGER_FEATURE_EDIT_FAILURE = "GROUPMANAGER_FEATURE_EDIT_FAILURE";
