// action type的命名规则：
// MODULE_PAGE_ACTION_OTHER
// 模块名_页面名_操作名_其他

//POPUP
export const CONTENT_POPUP_PROPS_SAVE_VALUE = "CONTENT_POPUP_PROPS_SAVE_VALUE";
export const CONTENT_POPUP_PROPS_SAVE_REQUEST = "CONTENT_POPUP_PROPS_SAVE_REQUEST";
export const CONTENT_POPUP_PROPS_SAVE_SUCCESS = "CONTENT_POPUP_PROPS_SAVE_SUCCESS";
export const CONTENT_POPUP_PROPS_SAVE_FAILURE = "CONTENT_POPUP_PROPS_SAVE_FAILURE";
export const CONTENT_POPUP_CLOSE_INFOBOX = 'CONTENT_POPUP_CLOSE_INFOBOX';
export const CONTENT_POPUP_GEOMETRY_SAVE_REQUEST = "CONTENT_POPUP_GEOMETRY_SAVE_REQUEST";
export const CONTENT_POPUP_GEOMETRY_SAVE_SUCCESS = "CONTENT_POPUP_GEOMETRY_SAVE_SUCCESS";
export const CONTENT_POPUP_GEOMETRY_SAVE_FAILURE = "CONTENT_POPUP_GEOMETRY_SAVE_FAILURE";

export const CONTENT_POPUP_DATA_DELETE_REQUEST = "CONTENT_POPUP_DATA_DELETE_REQUEST";
export const CONTENT_POPUP_DATA_DELETE_SUCCESS = "CONTENT_POPUP_DATA_DELETE_SUCCESS";
export const CONTENT_POPUP_DATA_DELETE_FAILURE = "CONTENT_POPUP_DATA_DELETE_FAILURE";

export const CONTENT_POPUP_ANNO_SAVE_REQUEST = "CONTENT_POPUP_ANNO_SAVE_REQUEST";
export const CONTENT_POPUP_ANNO_SAVE_SUCCESS = "CONTENT_POPUP_ANNO_SAVE_SUCCESS";
export const CONTENT_POPUP_ANNO_SAVE_FAILURE = "CONTENT_POPUP_ANNO_SAVE_FAILURE";

export const CONTENT_POPUP_FEATURE_SAVE_REQUEST = "CONTENT_POPUP_FEATURE_SAVE_REQUEST";
export const CONTENT_POPUP_FEATURE_SAVE_SUCCESS = "CONTENT_POPUP_FEATURE_SAVE_SUCCESS";
export const CONTENT_POPUP_FEATURE_SAVE_FAILURE = "CONTENT_POPUP_FEATURE_SAVE_FAILURE";



//MAPCOMPONENT
export const CONTENT_MAP_UPDATE_BOUNDS = "CONTENT_MAP_UPDATE_BOUNDS";
export const CONTENT_MAP_FETCH_DATA_REQUEST = "CONTENT_MAP_FETCH_DATA_REQUEST";
export const CONTENT_MAP_FETCH_DATA_SUCCESS = "CONTENT_MAP_FETCH_DATA_SUCCESS";
export const CONTENT_MAP_FETCH_DATA_FAILURE = "CONTENT_MAP_FETCH_DATA_FAILURE";
export const CONTENT_MAP_FETCH_PROPS_REQUEST = "CONTENT_MAP_FETCH_PROPS_REQUEST";
export const CONTENT_MAP_FETCH_PROPS_SUCCESS = "CONTENT_MAP_FETCH_PROPS_SUCCESS";
export const CONTENT_MAP_FETCH_PROPS_FAILURE = "CONTENT_MAP_FETCH_PROPS_FAILURE";
export const CONTENT_MAP_SAVE_GEODATA_REQUEST = "CONTENT_MAP_SAVE_GEODATA_REQUEST";
export const CONTENT_MAP_SAVE_GEODATA_SUCCESS = "CONTENT_MAP_SAVE_GEODATA_SUCCESS";
export const CONTENT_MAP_SAVE_GEODATA_FAILURE = "CONTENT_MAP_SAVE_GEODATA_FAILURE";
export const CONTENT_MAP_CLEAR_SELECTION = "CONTENT_MAP_CLEAR_SELECTION";
//TASKTABLE
export const CONTENT_MAP_TASK_QUERY_TASKLIST_REQUEST = "CONTENT_MAP_TASK_QUERY_TASKLIST_REQUEST";
export const CONTENT_MAP_TASK_QUERY_TASKLIST_SUCCESS = "CONTENT_MAP_TASK_QUERY_TASKLIST_SUCCESS";
export const CONTENT_MAP_TASK_QUERY_TASKLIST_FAILURE = "CONTENT_MAP_TASK_QUERY_TASKLIST_FAILURE";
export const CONTENT_MAP_TASK_OPEN_TASK_REQUEST = "CONTENT_MAP_TASK_OPEN_TASK_REQUEST";
export const CONTENT_MAP_TASK_OPEN_TASK_SUCCESS = "CONTENT_MAP_TASK_OPEN_TASK_SUCCESS";
export const CONTENT_MAP_TASK_OPEN_TASK_FAILURE = "CONTENT_MAP_TASK_OPEN_TASK_FAILURE";
export const CONTENT_MAP_TASK_CLOSE_TASK_REQUEST = "CONTENT_MAP_TASK_CLOSE_TASK_REQUEST";
//DRAWMANAGER
export const CONTENT_MAP_DRAWMANAGER_SAVE_KERNEL_REQUEST = "CONTENT_MAP_DRAWMANAGER_SAVE_KERNEL_REQUEST";
export const CONTENT_MAP_DRAWMANAGER_SAVE_KERNEL_SUCCESS = "CONTENT_MAP_DRAWMANAGER_SAVE_KERNEL_SUCCESS";
export const CONTENT_MAP_DRAWMANAGER_SAVE_KERNEL_FAILURE = "CONTENT_MAP_DRAWMANAGER_SAVE_KERNEL_FAILURE";


export const SELECT_MAP_PAGE = "SELECT_MAP_PAGE";
export const INVALIDATE_MAP_PAGE = "INVALIDATE_MAP_PAGE";
export const MAP_REQUEST = "MAP_REQUEST";
export const MAP_SUCCESS = "MAP_SUCCESS";
export const MAP_FAILURE = "MAP_FAILURE";
export const DRAW_ADD_MAP = "DRAW_ADD_MAP";

export const TASKS_REQUEST = "TASKS_REQUEST";
export const TASKS_SUCCESS = "TASK_SUCCESS";
export const TASKS_FAILURE = "TASK_FAILURE";