export const SELECT_TASKS_PAGE = "SELECT_TASKS_PAGE";
export const INVALIDATE_TASKS_PAGE = "INVALIDATE_TASKS_PAGE";

export const TASKS_REQUEST = "TASKS_REQUEST";
export const TASKS_SUCCESS = "TASK_SUCCESS";
export const TASKS_FAILURE = "TASK_FAILURE";