export const SYSMANAGER_ADDUSER_ADD_REQUEST = "SYSMANAGER_ADDUSER_ADD_REQUEST";
export const SYSMANAGER_ADDUSER_ADD_SUCCESS = "SYSMANAGER_ADDUSER_ADD_SUCCESS";
export const SYSMANAGER_ADDUSER_ADD_FAILURE = "SYSMANAGER_ADDUSER_ADD_FAILURE";
