export const SYSMANAGER_EDITUSER_UPDATE_REQUEST = "SYSMANAGER_EDITUSER_UPDATE_REQUEST";
export const SYSMANAGER_EDITUSER_UPDATE_SUCCESS = "SYSMANAGER_EDITUSER_UPDATE_SUCCESS";
export const SYSMANAGER_EDITUSER_UPDATE_FAILURE = "SYSMANAGER_EDITUSER_UPDATE_FAILURE";
