export const SELECT_GROUPS_PAGE = "SELECT_GROUPS_PAGE";
export const INVALIDATE_GROUPS_PAGE = "INVALIDATE_GROUPS_PAGE";

export const GROUPS_REQUEST = "GROUPS_REQUEST";
export const GROUPS_SUCCESS = "GROUPS_SUCCESS";
export const GROUPS_FAILURE = "GROUPS_FAILURE";

export const SAVE_GROUPS_INFO = "SAVE_GROUPS_INFO";
export const EDIT_GROUPS_INFO = "EDIT_GROUPS_INFO";
export const CLOSE_GROUPS_INFO = "CLOSE_GROUPS_INFO";

export const GROUP_INFO_POST = "GROUP_INFO_POST";
export const GROUP_INFO_SUCCESS = "GROUP_INFO_SUCCESS";
export const GROUP_INFO_FAILURE = "GROUP_INFO_FAILURE";
export const GROUP_DELETE_SUCCESS ="GROUP_DELETE_SUCCESS";
export const NEW_GROUPS_INFO = "NEW_GROUPS_INFO";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";