export const TASKMANAGER_TASKLIST_QUERY_REQUEST = "TASKMANAGER_TASKLIST_QUERY_REQUEST";
export const TASKMANAGER_TASKLIST_QUERY_SUCCESS = "TASKMANAGER_TASKLIST_QUERY_SUCCESS";
export const TASKMANAGER_TASKLIST_QUERY_FAILURE = "TASKMANAGER_TASKLIST_QUERY_FAILURE";
