

export const TASKINIT_REQUEST = "TASKINIT_REQUEST";
export const TASKINIT_SUCCESS = "TASKINIT_SUCCESS";
export const TASKINIT_FAILURE = "TASKINIT_FAILURE";

export const USERLIST_CHANGE = "USERLIST_CHANGE";
export const UPDATE_TASK_FILEDS = "UPDATE_TASK_FILEDS";

export const SAVE_TASKFIELD = "SAVE_TASKFIELD";
export const SAVE_TASKFIELD_REQUEST ="SAVE_TASKFIELD_REQUEST";
export const SAVE_TASKFIELD_SUCCESS ="SAVE_TASKFIELD_SUCCESS";
export const SAVE_TASKFIELD_FAILURE ="SAVE_TASKFIELD_FAILURE";

export const ADD_TASK_FILED = "ADD_TASK_FILED";
export const TASK_DESC_CHANGE ="TASK_DESC_CHANGE";
export const TASK_NAME_CHANGE ="TASK_NAME_CHANGE";

export const CHANGE_START_DATE = "CHANGE_START_DATE";
export const CHANGE_END_DATE = "CHANGE_END_DATE";
