export const GROUPMANAGER_ADDDICT_ADD_REQUEST = "GROUPMANAGER_ADDDICT_ADD_REQUEST";
export const GROUPMANAGER_ADDDICT_ADD_SUCCESS = "GROUPMANAGER_ADDDICT_ADD_SUCCESS";
export const GROUPMANAGER_ADDDICT_ADD_FAILURE = "GROUPMANAGER_ADDDICT_ADD_FAILURE";