export const GROUPMANAGER_FEATURE_ADD_REQUEST = "GROUPMANAGER_FEATURE_ADD_REQUEST";
export const GROUPMANAGER_FEATURE_ADD_SUCCESS = "GROUPMANAGER_FEATURE_ADD_SUCCESS";
export const GROUPMANAGER_FEATURE_ADD_FAILURE = "GROUPMANAGER_FEATURE_ADD_FAILURE";
