export const GROUPMANAGER_DICT_QUERY_REQUEST  ='GROUPMANAGER_DICT_QUERY_REQUEST';
export const GROUPMANAGER_DICT_QUERY_SUCCESS = 'GROUPMANAGER_DICT_QUERY_SUCCESS';
export const GROUPMANAGER_DICT_QUERY_FAILURE = 'GROUPMANAGER_DICT_QUERY_FAILURE';

export const GROUPMANAGER_DICT_USER_AVALIABLE_REQUEST  ='GROUPMANAGER_DICT_USER_AVALIABLE_REQUEST';
export const GROUPMANAGER_DICT_USER_AVALIABLE_SUCCESS = 'GROUPMANAGER_DICT_USER_AVALIABLE_SUCCESS';
export const GROUPMANAGER_DICT_USER_AVALIABLE_FAILURE = 'GROUPMANAGER_DICT_USER_AVALIABLE_FAILURE';

export const GROUPMANAGER_DICT_USER_DELETE_REQUEST = 'GROUPMANAGER_DICT_USER_DELETE_REQUEST';
export const GROUPMANAGER_DICT_USER_DELETE_SUCCESS = 'GROUPMANAGER_DICT_USER_DELETE_SUCCESS';
export const GROUPMANAGER_DICT_USER_DELETE_FAILURE = 'GROUPMANAGER_DICT_USER_DELETE_FAILURE';


export const GROUPMANAGER_DICT_ADD_USER_REQUEST = 'GROUPMANAGER_DICT_ADD_USER_REQUEST';
export const GROUPMANAGER_DICT_ADD_USER_SUCCESS = 'GROUPMANAGER_DICT_ADD_USER_SUCCESS';
export const GROUPMANAGER_DICT_ADD_USER_FAILURE = 'GROUPMANAGER_DICT_ADD_USER_FAILURE';