export const GROUPMANAGER_DICT_EDIT_REQUEST = "GROUPMANAGER_DICT_EDIT_REQUEST";
export const GROUPMANAGER_DICT_EDIT_SUCCESS = "GROUPMANAGER_DICT_EDIT_SUCCESS";
export const GROUPMANAGER_DICT_EDIT_FAILURE = "GROUPMANAGER_DICT_EDIT_FAILURE";
