

export const KERNEL_REQUEST = "KERNEL_REQUEST";
export const KERNEL_SUCCESS = "KERNEL_SUCCESS";
export const KERNEL_FAILURE = "KERNEL_FAILURE";

export const MEMBER_REQUEST = "MEMBER_REQUEST";
export const MEMBER_SUCCESS = "MEMBER_SUCCESS";
export const MEMBER_FAILURE = "MEMBER_FAILURE";

export const DATASOURCE_REQUEST = "DATASOURCE_REQUEST";
export const DATASOURCE_SUCCESS = "DATASOURCE_SUCCESS";
export const DATASOURCE_FAILURE = "DATASOURCE_FAILURE";
